- iocs/falsepositive-hashes.txt
- iocs/otx-hash-iocs.txt
https://www.virustotal.com/en/file/509155aac4177a73f0338d12b0810a89999425b6f3dc19c9dc7d40d320a9d438/analysis/
> Removing false positives (MsOffice2013 setlang.exe and Ahead Nero Drweb32.dll)

- README.md
- loki.py
Fixing https://github.com/Neo23x0/Loki/issues/20
add support for svchost owner in French system and corresponding changes to allow logging or avoid unicode errors, some extra dependencies/documentation when using loki.py on Windows
> Foreign language support: +French

- loki.py
> unicode support

- .gitmodules
- loki.py
- requirements.txt
> Revert "Revert 45 master"

- loki.py
previous commit mangled utf8 french chars
https://github.com/Neo23x0/Loki/commit/c6612593f02c01c484000fa79217935277aef560
fixing and adding regexp match just in case
> fix french locale matching utf8+regex

- tools/vt-checker-hosts.py
- tools/vt-checker.py
Just a typo fix.
Hope you're having a great day! :)
> Fix a typo: loosing -> losing

- lib/helpers.py
fixed minor bugs
wanna run in windows python 3.5
> minor changes in helper.py for getting compatible with python 3.5 

- lib/lokilogger.py
Minor bug fixes 
(on running this file manually with python3.5)
> minor changes in lokilogger.py for compatibility with python 3.5 

- loki-upgrader.py
> minor changes in loki-upgrader.py for compability with python 3.5

- lib/lokilogger.py
by checking sys.stdout.encoding for None and falling back to utf-8
> fix for issue #87

- README.md
- build.bat
- lib/privrules.py
- loki-noprivrules.spec
- loki-package-builder.py
- loki-privrules.spec
- loki.py
Allows LOKI to be built with custom rulesets embedded in the LOKI package.
> Mirar dev private rules

- loki.py
the svchost.exe when run with -k UnistackSvcGroup was not recognized, had to lower() the string in oder not to show false positive
> svchost.exe check in mem-scan

- .travis.yml
- README.md
- build.bat
- lib/lokilogger.py
- lib/pesieve.py
- loki-upgrader.py
- loki.py
- requirements.txt
Added some additional features required to make the tool scale well within our environment. Mainly, the ability to run the tool from a remote location, which keeps the host clean for forensics reasons, and push all results to a remote file share or to Splunk (or whatever) via TCP syslog.
- Added --syslogtcp, allowing TCP syslog servers, was easier with our Splunk setup
- Included pywin32, setuptools==19.2, and rfc5424-logging-handler in pip command, latter to enable rfc5424 compatible syslog logging
- Fixed exception handler for #51 (not sure why this triggered for me since there is a check before this func is called in init, might be because subfolder didn't exist for some reason)
- Added date and time to default filename
- Added ability to specify log directory independant of filename, …
> Some, hopefully, useful extra features

- lib/lokilogger.py
- lib/pesieve.py
- loki.py
@hasherezade advised against making /shellc default due to false positives, made it optional with a switch to enable. Increased version number.
> Implemented @hasherezade recommendation.

- lib/lokilogger.py
Loki shows version 0.30.6 when launching, but the code is tagged as 0.30.7
> Fix version according to latest git tag

- build.bat
Fixed the variable name for python.exe.
> fixed python.exe location

- tools/vt-checker-hosts.py
- tools/vt-checker.py
[`python3 -m pip install future`](https://pypi.org/project/future)
[`futurize -f lib2to3.fixes.fix_except -f libfuturize.fixes.fix_print_with_import -w ./tools/vt-checker.py ./tools/vt-checker-hosts.py`](https://python-future.org/futurize.html)
> Use print() function in both Python 2 and Python 3

- loki.py
Add option to call other python bin (for platforms which don't link python2/3 by default, such as kali)
> Add option to call other python bin

- loki.py
Fixed issue: https://github.com/Neo23x0/Loki/issues/197
> Fixed comparison issue

- .github/workflows/lint_python.yml
- loki.py
- test/yara/JFolder.jsp
> add version option

- .github/workflows/lint_python.yml
changes proposed by @cclauss in 
https://github.com/Neo23x0/Loki/pull/229#event-8915656009
> Replace flake8, isort, and pyupgrade with ruff

- lib/lokilogger.py
Code for version 0.51.0 has a wrong value for its version label ("0.50.1").
> Fix version label

- loki.py
> add warning if file is skipped because of file size
